### ISSUE TITLE
OS environment 

### ISSUE THREAD

**Issue by akheiri123** [rte-france/challenge-roadef-2020#13]
Hello,
Given my little experience on working with Linux environment, would it be possible for me to design a solution under windows OS?

**Comment by klorel** [comment]
Hi!
In order to be fair to everybody, the computational evaluation will be done on a unique OS system, and LINUX is one of the most used in computer where performance is really important.
As you may have understood, there won't  be evaluations done on Windows OS.
PS: be aware that python, C++, java and a lot of Framework can be used in linux or Windows very easily.

Manuel
